home:
  path: /
  controller: App\Controller\HomeController::index

property.list:
  path: /acheter
  controller: App\Controller\PropertyController::list

property.detail:
  path: /acheter/{slug}-{id}
  requirements: 
    slug: '[a-z0-9\-]*'
  controller: App\Controller\PropertyController::detail

admin:
  path: /admin
  controller: App\Controller\SecurityController::login

logout:
  path: /deconnexion

admin.property.list:
  path: /admin/property
  controller: App\Controller\Admin\AdminPropertyController::list

admin.property.create:
  path: /admin/property/create
  controller: App\Controller\Admin\AdminPropertyController::create

admin.property.edit:
  path: /admin/property/{id}
  methods: GET|POST
  controller: App\Controller\Admin\AdminPropertyController::edit

admin.property.delete:
  path: /admin/property/{id}
  methods: DELETE
  controller: App\Controller\Admin\AdminPropertyController::delete
